# Generated by Django 6.0.5 on 2026-05-21 07:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('bio', models.TextField(blank=True, default='', max_length=500)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('experience', models.JSONField(blank=True, default=list)),
                ('template_style', models.CharField(choices=[('minimal', 'Minimal Grid'), ('bold', 'Bold Asymmetric'), ('classic', 'Classic Swiss')], default='minimal', max_length=20)),
                ('slug', models.SlugField(editable=False, max_length=160, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
